import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import { useForm } from "react-hook-form";
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isOrderCheckout, setIsOrderCheckout] = useState()
  const { register, handleSubmit, watch, formState: { errors } } = useForm();
  const onSubmit = async (data) => {
    try {
      const options = {
        method: 'POST',
        headers: {
          Accept: 'application/vnd.conekta-v2.0.0+json',
          'Content-Type': 'application/json',
          'Accept-Language': 'es',
          Authorization: `Basic ${process.env.CONEKTA_TOKEN_BASE_64}`
        },
        body: JSON.stringify({
          name: data.name,
          email: data.email,
          phone: data.phone,
          typePayment: data.typePayment,
          amount: data.amount
        })
      }
      const response = await fetch('/api/create-order', options)
      const dataJson = await response.json()
      setIsOrderCheckout(dataJson.checkout_id)
    } catch (error) {
      
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"></link>
      </Head>
      <Script src='https://pay.conekta.com/v1.0/js/conekta-checkout.min.js' />
      <main className={styles.main}>
        <div>
          <h1>Conekta</h1>
        </div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="mb-3">
            <label  className="form-label">Email address</label>
            <input type="email" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" {...register('email', { required: true })} />
            {
              errors.email?.type === 'required' && <small className='text-danger'>Campo requerido</small>
            }
          </div>
          <div className="mb-3">
            <label className="form-label">Telefono</label>
            <input type="tel" className="form-control" id="exampleInputPassword1" {...register('phone', { required: true})} />
            {
              errors.phone?.type === 'required' && <small className='text-danger'>Campo requerido</small>
            }
          </div>
          <div className="mb-3">
            <label className='form-label'>Nombre</label>
            <input type="text" className='form-control' {...register('name', { required: true })} />
            {
              errors.name?.type === 'required' && <small className='text-danger'>Campo requerido</small>
            }
          </div>
          <div className="mb-3">
            <label className='form-label'>Tipo de Pago</label>
            <input type="text" className='form-control' {...register('typePayment', { required: true })} />
            {
              errors.typePayment?.type === 'required' && <small className='text-danger'>Campo requerido</small>
            }
          </div>
          <div className="mb-3">
            <label className='form-label'>Tipo de Pago</label>
            <input type="number" className='form-control' {...register('amount', { required: true })} />
            {
              errors.amount?.type === 'required' && <small className='text-danger'>Campo requerido</small>
            }
          </div>
          <button type="submit" className="btn btn-primary">Submit</button>
        </form>
      </main>
      <div id="conektaIframeContainer" style={{height: '700px'}}></div>
            {
              isOrderCheckout && (
                <Script type="text/javascript" id='conekta' strategy='afterInteractive'>
                  {`
                    window.ConektaCheckoutComponents.Integration({
                      targetIFrame: "#conektaIframeContainer",
                      checkoutRequestId: "${isOrderCheckout}", //Checkout ID enviado desde el servidor para inicializar el componente de pago.
                      publicKey: "key_M3W1Y6QVlLZThLUN8XH3URp",
                      options: {},
                      styles: {},
                      onFinalizePayment: function (event) {
                          console.log(event);
                      }
                    })
                  `}
              </Script>
              )
            }
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossOrigin="anonymous" />
    </>
  )
}
